### ISSUE TITLE
Can't create Moodle job

### ISSUE THREAD

**Issue by fjungwirth** [backmeup/backmeup-prototype#79]
Trying to create a Moodle job fails, even though I'm passing the correct login information.
I get the following message: "Some error occured."

**Comment by WolfgangEibner** [comment]
Facebook job is also not possible (same error message).

Info from embedded.log:

```
INFO: Making a GET request to https://graph.facebook.com/me?access_token=5183999&format=json
Nov 7, 2012 4:11:18 PM com.restfb.DefaultFacebookClient makeRequestAndProcessResponse
INFO: Facebook responded with HTTP status code 400 and response body: {"error":{"message":"Invalid OAuth access token.","type":"OAuthException","code":190}}
org.backmeup.model.exceptions.PluginException: An exception occured during execution of the method postAuthorize
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:230)
        at $Proxy88.postAuthorize(Unknown Source)
        at org.backmeup.logic.impl.BusinessLogicImpl.postAuth(BusinessLogicImpl.java:992)
        at org.backmeup.logic.impl.BusinessLogicImpl$Proxy$_$$_WeldClientProxy.postAuth(BusinessLogicImpl$Proxy$_$$_WeldClientProxy.java)
        at org.backmeup.rest.Datasources.postAuthenticate(Datasources.java:156)
        at sun.reflect.GeneratedMethodAccessor229.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
        at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:257)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:222)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:211)
        at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:525)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:502)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
        at org.jboss.resteasy.plugins.server.tjws.TJWSServletDispatcher.service(TJWSServletDispatcher.java:40)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2326)
        at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2280)
        at Acme.Serve.Serve$ServeConnection.run(Serve.java:2052)
        at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1402)
        at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:228)
        ... 24 more
Caused by: org.backmeup.model.exceptions.PluginException: An error occurred while retrieving authentication information
        at org.backmeup.facebook.FacebookAuthenticator.postAuthorize(FacebookAuthenticator.java:93)
        ... 28 more
Caused by: com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: Invalid OAuth access token.
        at com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:643)
        at com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:564)
        at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:509)
        at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:469)
        at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:428)
        at com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:238)
        at org.backmeup.facebook.FacebookAuthenticator.postAuthorize(FacebookAuthenticator.java:89)
        ... 28 more
Nov 7, 2012 4:11:28 PM com.restfb.DefaultWebRequestor executeGet
INFO: Making a GET request to https://graph.facebook.com/me?access_token=5183988&format=json
Nov 7, 2012 4:11:28 PM com.restfb.DefaultFacebookClient makeRequestAndProcessResponse
INFO: Facebook responded with HTTP status code 400 and response body: {"error":{"message":"Invalid OAuth access token.","type":"OAuthException","code":190}}
org.backmeup.model.exceptions.PluginException: An exception occured during execution of the method postAuthorize
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:230)
...
```

**Comment by WolfgangEibner** [comment]
@fetzig , @fjungwirth: Anything new on that?

**Comment by fjungwirth** [comment]
I can start a Facebook and a Twitter job, but a new job is created every minute and i got about 60 notification mails that the job didn't work. I only stopped this by deleting the bmu dropbox app's access permissions on my dropbox

**Comment by keros** [comment]
I have also tried to create an facebook to dropbox job but I get an Error Site

```
KeyError at /job/create/

'jobId'

Request Method:     POST
Request URL:    http://www.backmeup.at/job/create/
Django Version:     1.4.2
Exception Type:     KeyError
Exception Value:    

'jobId'

Exception Location:     /data/backmeup-frontend/project/main/forms.py in rest_save, line 314
Python Executable:  /usr/bin/python
...
```

**Comment by ghost** [comment]
I just tried to run a facebook job manually via REST, but it fails during POST-Authorization:

```
org.backmeup.model.exceptions.PluginException: An exception occured during execution of the method postAuthorize
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:229)
        at $Proxy84.postAuthorize(Unknown Source)
        at org.backmeup.logic.impl.BusinessLogicImpl.postAuth(BusinessLogicImpl.java:998)
        at org.backmeup.logic.impl.BusinessLogicImpl$Proxy$_$$_WeldClientProxy.postAuth(BusinessLogicImpl$Proxy$_$$_Weld
ClientProxy.java)
        at org.backmeup.rest.Datasources.postAuthenticate(Datasources.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
        at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:257)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:222)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:211)
        at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:525)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:502)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:
208)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
        at org.jboss.resteasy.plugins.server.tjws.TJWSServletDispatcher.service(TJWSServletDispatcher.java:40)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2326)
        at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2280)
        at Acme.Serve.Serve$ServeConnection.run(Serve.java:2052)
        at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1402)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:227)
        ... 25 more
Caused by: org.backmeup.model.exceptions.PluginException: An error occurred while retrieving authentication information
        at org.backmeup.facebook.FacebookAuthenticator.postAuthorize(FacebookAuthenticator.java:93)
        ... 30 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://graph.facebook.com/oauth/access
_token?client_id=213557938748364&redirect_uri=http://www.backmeup.at/oauth_callback&client_secret=a54e75c9dfae113789a509
f6794cbe1f&code=AQC92ycOmK_oJlmfSEzQLyzByixMi4j1ocH2EqD6JFFFtxXGnHWQJQ0F4UIGeyOKxYqlEkjmKqMyqQ7eq_dCHJ3KZm5YIEXHTYOxJ4sq
T38w-ZhIQQoVVU94wSWY7yYZJHJRd9g6EmoG3u7n8ekbgKKL0-Hr0w7J3Y5kDPWXU4Fe5u0hp8UnISLir8Tvc1Eop97pkBrGTYI7F9EhXXl9tOz7
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1436)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
        at org.backmeup.facebook.FacebookAuthenticator.postAuthorize(FacebookAuthenticator.java:67)
        ... 30 more
```

The call to http://graph.facedbook.com/oauth/accses_token returns BAD REQUEST 400.
You might reproduce this yourself by running the following script: 

```
cd python-tests
python TestFacebookWithOptions.py
```

**Comment by ghost** [comment]
Testing the script on dev02 results in following error message:

```
...
   "Caused by: com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: Invalid OAuth access token.",
    "\tat com.restfb.DefaultFacebookClient$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookClient.java:643)",
    "\tat com.restfb.DefaultFacebookClient.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookClient.java:564)",
    "\tat com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:509)",
    "\tat com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:469)",
    "\tat com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:428)",
    "\tat com.restfb.DefaultFacebookClient.fetchObject(DefaultFacebookClient.java:238)",
    "\tat org.backmeup.facebook.FacebookAuthenticator.postAuthorize(FacebookAuthenticator.java:89)",
```

The facebook.properties file contains the key & secret which you described at Plone. As code argument I use the one returned by facebook.

**Comment by ghost** [comment]
Running Moodle with the auth data provided on Plone results in following exception during the backup:

```
STATUS:
STATUS:
http://gtn02.gtn-solutions.com/moodle20/blocks/backmeup/service.php?username=backmeup&password=286bafbb1a9faf4dc4e104a33e222304&action=list
STATUS: An exception occured during execution of the method downloadAll
java.io.FileNotFoundException: http://gtn02.gtn-solutions.com/moodle20/blocks/backmeup/service.php?username=backmeup&password=286bafbb1a9faf4dc4e104a33e222304&action=list
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1401)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:654)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:189)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:783)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:748)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:239)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:288)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:177)
        at org.backmeup.moodle.MoodleValidator.validate(MoodleValidator.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:227)
        at $Proxy87.validate(Unknown Source)
        at org.backmeup.logic.impl.BusinessLogicImpl.validateProfile(BusinessLogicImpl.java:1187)
        at org.backmeup.logic.impl.BusinessLogicImpl.validateBackupJob(BusinessLogicImpl.java:1227)
        at org.backmeup.logic.impl.BusinessLogicImpl.createBackupJob(BusinessLogicImpl.java:729)
        at org.backmeup.logic.impl.BusinessLogicImpl$Proxy$_$$_WeldClientProxy.createBackupJob(BusinessLogicImpl$Proxy$_$$_WeldClientProxy.java)
        at org.backmeup.rest.BackupJobs.createBackupJob(BackupJobs.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
        at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:257)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:222)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:211)
        at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:525)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:502)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
        at org.jboss.resteasy.plugins.server.tjws.TJWSServletDispatcher.service(TJWSServletDispatcher.java:40)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2326)
        at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2280)
        at Acme.Serve.Serve$ServeConnection.run(Serve.java:2052)
        at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1402)
        at java.lang.Thread.run(Thread.java:679)
```

**Comment by fjungwirth** [comment]
the moodle error was caused by the moodle installation and is fixed now

**Comment by WolfgangEibner** [comment]
Moodle error seems to be fixed. Still having a facebook error.

**Comment by WolfgangEibner** [comment]
Facebook error should also be fixed now.
